version: '3.8'

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
